### PR TITLE
Use Quill for Editor in Camino Creator

### PR DESCRIPTION
**Pull request by jxjj**
In the update to Vue3, the prior `Vue2Editor` component was replaced with a simple text area and basic markdown support.

This PR now adds a better editor –  one based on Quill and the components we developed in ChimeIn. Image upload support is included (but no LaTeX formulas... though a tour with math is an interesting idea!).

I tweaked the default "snow" style a bit... I was feeling overwhelmed by borders and boxes.

Creator View:
Screen Shot 2022-06-29 at 3 46 08 PM

Rendered page:
Screen Shot 2022-06-29 at 3 47 20 PM

### CODE REVIEW

**Comment by cmcfadden** [comment]
Looks good, but we don't want image uploading in the editor, so back that stuff out. It creates problems for multilingual tours (you end up needing to load the image multiple times) and creates a situation where different images behave differently for the consumer, which isn't clear.

**Comment by jxjj** [comment]
Hmmm...  I see your point about multilingual tours. 

I was thinking the image upload in the editor would be useful for #76, so I might not back it out of the editor, but instead hide it behind a props?

**Comment by cmcfadden** [comment]
That makes sense.

**Comment by jxjj** [comment]
Image upload now a prop on VEditor. Removed in the LanguageText component.

Screen Shot 2022-06-30 at 1 03 47 AM

Also: constrained line length a bit within the editor.

**Pull request merged**
