### PR TITLE
Update Map Location and Route Selector

### LINKED ISSUE #120: Creator: tour stop map component issues:
- [ ] #224
- [x] #223
- [x] #222
- [x] There should be a "Save" or "Done" button on the modal.
- [x] The current default location is 0,0. Use previous location, tour start location if known. A better fallback might be UMN campus.

### LINKED ISSUE #223: tour path doesn't follow the stop

### LINKED ISSUE #224: clicking location doesn't always update stop (red dot)

### PR DESCRIPTION
**Pull request by jxjj**
This reworks the `<LocationSelector>` component which was a bit broken after the Vue3 update. 

The previous component was responsible for selecting locations and letting the user draw routes between locations, and based on [Leaflet](https://github.com/Leaflet/Leaflet).

In this PR, we rework in a more declarative style, splitting the functionality among a few different components, and reusing Camino Trekker Map components (which are based on MapboxGL).

### `<MapMarkerLabel>`

Screen Shot 2022-06-27 at 9 57 50 PM

 A custom marker label for a map.
	- Stop number in the style of Camino Trekker stop labels
	- `color`: stop markers can be colored pink (active), gray (inactive), or orange (highlighted).
	- `pulse`: stops can emit a subtle pulse animation to draw the user's attention.

### `<MapMarker>`
Contains the label and popup.
- `draggable` prop allows the user  to drag the marker around.
- `@drag` event lets us update the location on drag end.

I'm not a fan of the drag/move icon I used. That's something to fix later. I wanted some affordance/signifier, but this doesn't look right...

### `<MapPolylineEditable>` 

Screen Shot 2022-06-27 at 10 04 01 PM

Creates editable polylines, which we can use for drawing routes. The user can move waypoints or click on a midpoint to create a new waypoint (similar to old functionality). Moving a targetPoint will update the polyline. The target pulses.

### `<MapboxLocationSelector>` 

Screen Shot 2022-06-27 at 9 12 28 PM

Similar to the previous location selector, but used for selecting just locations (see `<NavStageMapper>` for Location + Route).
	- will show the tour routes and stops if passed a `tourId`, so that the user has some context
	- No longer uses a modal
	- Has a movable location selector (clicking works too)
	- Updated Lng/Lat display

### `<NavStageMapper>`

Screen Shot 2022-06-27 at 9 12 56 PM

This lets the user select target points and draw routes. Users can also clear route and target points, and use current location.

### `<TourMap>`

The advantage to the new stop labels is that they could be used in Camino Trekker (rather than boring default markers). The Tour Map and Stop maps have been updated with the new style.

In addition to the stop numbers, pulses and color, the line segment has a gradient to imply directionality:

Screen Shot 2022-06-27 at 9 13 23 PM

Looks nice with the light background.
Screen Shot 2022-06-27 at 9 13 58 PM

## Other Changes
- A bit of JS to TS conversion. Very helpful in ensuring I'm checking for nulls and adding `.value` to my refs. Also: autocompletion is rad. 
- refactored CreatorStore
- some test fixes (and a few more to come before this PR is merged, I'm sure)

Latest Version up on https://cla-camino-dev.oit.umn.edu/

Closes #120
Closes #224 
Closes #223

### CODE REVIEW

**Review by cmcfadden — COMMENTED** [review]
Definitely agree the drag handle is odd. I think it's fine to just drop the drag indicator part of it - folks will understand. 

I played around with this a bit on dev. The geolocation button seems to behave a bit odd-  it's always disabled on safari for me, and just spun on chrome, but the "use current location" button worked correctly on both. Can break that into a separate issue if it's easier.

Poking around with a test tour (#30 on dev), it seems like the tour creator map renders a bit differently from the stop maps / trekker maps. See screenshots of tour creator vs trekker. Numbers are different and line segment is broken.

Screen Shot 2022-06-28 at 7 05 52 AM
Screen Shot 2022-06-28 at 7 08 28 AM
Screen Shot 2022-06-28 at 7 08 28 AM

**Comment by jxjj** [comment]
I appreciate the testing and critical feedback, @cmcfadden. I'll take a look. 

I also think I'm going to ditch the click handler on the RouteMapper component (but keep it on the Location selector):
-  dragging is easy and intuitive. 
- the use case for clicking is limited since once the start point is selected, users will be in the right general area.
- there's not a great way to prevent route edit clicks accidentally triggering an update target point, which is a bit frustrating when it happens.
- clicks interfere with selecting individual route points for deletion.

The alternative is adding a listener to each layer, to catch the Map click event before it propagates, but that seems like it might be pretty brittle.

**Comment by jxjj** [comment]
- [x] Tests updated
- [x] Remove the drag handle on the location indicator
- [x] Remove click to update location in Nav Stage Mapper
- [x] Location Selector missing first segment fixed. I blame Github Copilot – it's very good at suggesting code that looks right, but is subtly wrong. (My reduce function should have returned the first point as the base case, not the accumulator).
- [x] Some null values have crept into tour routes that were causing some headaches. I added a [`normalizeTour` function](resources/shared/normalizeTour.ts) to clean up the data on initial fetch, making sure that routes are well-defined and continuous. This fn could use a test or two eventually.

The Mapbox GeolocateControl is strange. I see the same behavior. I notice that when I navigate to a new tab and then navigate back, my stop updates.

Thanks again for your help with this! LMK if you see any additional changes or needed fixes before merging.

**Review by cmcfadden — APPROVED** [review]
Looks good to merge. I don't see any issues with the routing logic, but if we end up chasing our tails on edge case stuff, we can think about bigger refactors of how that's managed - it's right on the edge of what I'm comfortable with in terms of complexity. 

Good work on this!

**Comment by jxjj** [comment]
Thanks and agreed. 

One direction for future work might be to migrate navigation info into core stop content, rather than a stage. Then we can make some guarantees that every stop will have a target point and route (and only one). This would reduce the amount of stage parsing, which should allow us to remove a bunch of code.

**Pull request merged**
